framework:
    messenger:
        failure_transport: failed

        transports:
<<<<<<< HEAD
            # https://symfony.com/doc/current/messenger.html#transport-configuration
=======
>>>>>>> master
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
<<<<<<< HEAD
            # sync: 'sync://'
=======
            sync: 'sync://'  # UNCOMMENT THIS LINE
>>>>>>> master

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
<<<<<<< HEAD
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
=======
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync  # CHANGE FROM async TO sync
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
>>>>>>> master
